[package]
name = "cartorio"
version = "0.1.0"
authors = ["Ciro S. Costa <cscosta@pivotal.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

hyper = "0.12"
clap = "2.0"
futures = "0.1.25"
serde_json = "1.0"
