platform: linux

image_resource:
  type: registry-image
  source: 
    repository: library/rust
    tag: '1.33'

params:
  RUST_BACKTRACE: full

inputs:
- name: repository
  path: .

outputs:
- name: binary
  path: bin

run: 
  path: cargo 
  args:
    - install 
    - --path=. 
    - --root=.
