---
platform: linux

image_resource:
  type: registry-image
  source: {repository: 'rust:1.33'}

params:
  TARGET: ~

inputs:
- name: repository
  path: .

outputs:
- name: target

run: {path: ./ci/tasks/scripts/build.sh}
