resource_types:
- name: semver
  type: registry-image
  source:
    repository: concourse/semver-resource


resources:
  - name: repository
    type: git
    source:
      uri: https://((github-token))@github.com/cirocosta/cartorio
      ignore_paths: [ ./VERSION ]

  - name: container-image
    type: registry-image
    source:
      repository: cirocosta/cartorio
      username: ((docker-user))
      password: ((docker-password))

  - name: version
    type: semver
    source:
      driver: git
      uri: https://((github-token))@github.com/cirocosta/cartorio
      branch: master
      file: ./VERSION
      git_user: Ciro S. Costa <cscosta@pivotal.io>


jobs:
  - name: build
    public: true
    serial: true
    plan:
      - in_parallel:
        - get: repository
          trigger: true
        - get: version
      - in_parallel:
          fail_fast: true
          steps:
            - task: build-image
              privileged: true
              file: repository/ci/tasks/build-image.yml
            - task: build-linux-gnu
              file: repository/ci/tasks/build.yml
              params: { TARGET: x86_64-unknown-linux-gnu }
            - task: integration
              privileged: true
              file: repository/ci/tasks/integration.yml
      - put: container-image
        inputs: [image, version]
        get_params: {format: oci}
        params:
          image: image/image.tar
          additional_tags: version/version
