resources:
  - name: repository
    type: git
    source:
      uri: https://((github-token))@github.com/cirocosta/cartorio

  - name: container-image
    type: registry-image
    source:
      repository: cirocosta/cartorio
      username: ((docker-user))
      password: ((docker-password))


jobs:
  - name: build
    public: true
    serial: true
    plan:
      - get: repository
        trigger: true
      - task: build-image
        privileged: true
        file: repository/ci/tasks/build-image.yml
      - put: container-image
        inputs: [image]
        get_params: {format: oci}
        params: {image: image/image.tar}
