resource_types:
- name: semver
  type: registry-image
  source:
    repository: concourse/semver-resource


resources:
  - name: repository
    type: git
    source:
      uri: https://((github-token))@github.com/cirocosta/cartorio
      ignore_paths: [ ./VERSION ]

  - name: integration-image-dockerfile
    type: git
    source:
      uri: https://((github-token))@github.com/cirocosta/cartorio
      ignore_paths: [ ./ci/dockerfiles/integration/Dockerfile ]

  - name: builder-task
    type: git
    source:
      uri: https://github.com/concourse/builder-task

  - name: integration-image
    type: registry-image
    source:
      repository: cirocosta/cartorio-integration
      username: ((docker-user))
      password: ((docker-password))

  - name: container-image
    type: registry-image
    source:
      repository: cirocosta/cartorio
      username: ((docker-user))
      password: ((docker-password))

  - name: version
    type: semver
    source:
      driver: git
      uri: https://((github-token))@github.com/cirocosta/cartorio
      branch: master
      file: ./VERSION
      git_user: Ciro S. Costa <cscosta@pivotal.io>


jobs:
  - name: integration-image
    public: true
    serial: true
    plan:
      - in_parallel:
        - get: builder-task
          trigger: true
        - get: repository
          resource: integration-image-dockerfile
          trigger: true
      - task: build
        privileged: true
        input_mapping: { builder: repository }
        file: builder-task/example.yml
        params:
          CONTEXT: builder/ci/dockerfiles/integration
      - put: integration-image
        inputs: [image]
        get_params: {format: oci}
        params:
          image: image/image.tar

  - name: build
    public: true
    serial: true
    plan:
      - in_parallel:
        - get: repository
          trigger: true
        - get: version
          trigger: true
        - get: integration-image
          passed: [ 'integration-image' ]
          trigger: true
      - task: build-linux-gnu
        file: repository/ci/tasks/build.yml
      - in_parallel:
        - task: build-image
          privileged: true
          file: repository/ci/tasks/build-image.yml
        - task: test
          file: repository/ci/tasks/build-image.yml
        - task: integration
          image: integration-image
          privileged: true
          file: repository/ci/tasks/integration.yml
      - put: container-image
        inputs: [image, version]
        get_params: {format: oci}
        params:
          image: image/image.tar
          additional_tags: version/version

